name: Setup Nix
description: Install upstream Nix and enable the native GitHub Actions cache

runs:
  using: composite
  steps:
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
      with:
        # Determinate Nix attempts a FlakeHub login even though this repository
        # uses the native GitHub Actions cache.
        determinate: false
    - name: Enable Nix cache
      uses: DeterminateSystems/magic-nix-cache-action@908b263ff629f4cc17666315b7fd3ec127c6244d # v14
